from .registration_service import welcome, get_user_faculty_service, get_user_group_service, write_user_service
from .schedule_service import schedule_this_week_service, schedule_next_week_service, schedule_this_day_service, schedule_next_day_service
