from array import typecodes
import sqlite3
import typing
from aiogram import BaseMiddleware
import aiosqlite
import abc
import psycopg
import asyncio
import os

from sqlalchemy.engine.base import Connection
from sqlalchemy.orm import immediateload
from config import DBNAME, USER, PASSWORD, HOST, PORT
from psycopg_pool import ConnectionPool, AsyncConnectionPool
from loguru import logger

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text


from database.models import User, AsyncSessionLocal
#------------------------TO DO ---------------------------
#
#1. how to make several connection? because ask for conn every time from the func is a bad thing, so we never do in the postgres
#
#
#
#
#__________________________________________________________




class DBConnect(abc.ABC):
    @staticmethod
    def get_conn() -> typing.Any:
        pass


class DBTablesCreator(abc.ABC):
    @staticmethod
    @abc.abstractmethod
    async def create(pool) -> None:
        pass



class DBFillTable(abc.ABC):
    @staticmethod
    @abc.abstractmethod
    async def fill(*args, **kwargs) -> None:
        pass



class DBCRUD(abc.ABC):
    pass


class SQLiteConnect(DBConnect):
    async def get_conn(self) -> sqlite3.Connection:#type:ignore IGNORE BECAUSE SQLITE CONNECTION IS NOT REALISED
        pass

#DO we need to class remember his conn?
@typing.final
class PostgreConnect(DBConnect):
    @staticmethod
    def get_alchemy_conn() -> AsyncSession:
        connection = AsyncSessionLocal()

        
        return connection

    @staticmethod
    async def get_async_pool():

        logger.info(f'trying to connect with {DBNAME}\t{USER}\t{HOST}\t{PORT}')
        pool = AsyncConnectionPool(conninfo=f"""
            dbname={DBNAME}
            user={USER}
            password={PASSWORD}
            host={HOST}
            port={PORT}
            sslmode=disable
            gssencmode=disable""",
            min_size=4,
            max_size=10
        )
        
        logger.info('Succes connection')

        return pool



#ADD HERE -> WHAT WE ARE WAITING HERE
@typing.final
class PostgreDBTablesCreation(DBTablesCreator):
    @staticmethod
    async def create(pool) -> None:
        try:
            logger.info('Creating the tables')

            async with pool.connection() as conn:
                async with conn.cursor() as cur:
                    await cur.execute("""CREATE TABLE IF NOT EXISTS all_groups(
                        db_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        group_id INT NOT NULL,
                        group_name VARCHAR(20) NOT NULL,
                        faculty_id INT NOT NULL,
                        course INT NOT NULL
                    )""")

                    await cur.execute("""CREATE TABLE IF NOT EXISTS groups_in_use(
                        db_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        group_id INT NOT NULL,
                        group_name VARCHAR(20) NOT NULL,
                        faculty_id INT NOT NULL,
                        course INT NOT NULL
                    )""")
                    
                    await conn.commit()

                    logger.info('Tables created')

        except Exception as e:
            logger.exception('Creation trouble', e)


#    @staticmethod
#    async def fill_tables(pool, to_insert:list) -> None: #to_insert is list of dicts
#        try:
#            with pool.connection as conn:
#                with conn.cursor as cur:
#                    await cur.executemany("INSERT INTO all_groups(group_id, group_name, faculty_id, course) VALUES (%s, %s, %s, %s)", to_insert)
#                    await conn.commit()
#
#        except Exception as e:
#            logger.critical("Cant fill the tables", e)






@typing.final
class PostgreFillTablesCreation(DBFillTable):
    @staticmethod
    async def fill(pool, to_insert: list) -> None:
        try:
            async with pool.connection() as conn:
                async with conn.cursor() as cur:
                    await cur.executemany("INSERT INTO all_groups(group_id, group_name, faculty_id, course) VALUES (%s, %s, %s, %s)", to_insert)
                    await conn.commit()

        except Exception as e:
            logger.opt(exception=e).critical("Cant fill the tables")





class AlchemyMiddleware(BaseMiddleware):
    def __init__(self, session_factory):
        self.session_factory = session_factory

    async def __call__(self, handler, event, data):
        async with self.session_factory() as session:
            data["session"] = session
            return await handler(event, data)


class AsyncpgMiddleware(BaseMiddleware):
    def  __init__(self, pool):
        self.pool = pool

    async def __call__ (self, handler, event, data):
        async with self.pool.acquire() as conn:
            data["conn"] = conn
            await handler(event, data)
        










