import sqlite3
import typing
import aiosqlite
import abc
import psycopg
import asyncio
import os

from sqlalchemy.engine.base import Connection
from sqlalchemy.orm import immediateload
from config import DBNAME, USER, PASSWORD, HOST, PORT
from psycopg_pool import ConnectionPool
from models import User, AsyncSessionLocal
from loguru import logger

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import text
#------------------------TO DO ---------------------------
#
#1. how to make several connection? because ask for conn every time from the func is a bad thing, so we never do in the postgres
#
#
#
#
#__________________________________________________________




class DBConnect(abc.ABC):
    @staticmethod
    def get_conn() -> typing.Any:
        pass


class DBTablesCreator(abc.ABC):
    pass

class DBCRUD(abc.ABC):
    pass


class SQLiteConnect(DBConnect):
    async def get_conn(self) -> sqlite3.Connection:#type:ignore IGNORE BECAUSE SQLITE CONNECTION IS NOT REALISED
        pass

#DO we need to class remember his conn?
class PostgresConnect(DBConnect):
    @staticmethod
    def get_alchemy_conn() -> AsyncSession:
        connection = AsyncSessionLocal()

        
        return connection

    @staticmethod
    def get_pool():

        pool = ConnectionPool(conninfo="""
            dbname=DBNAME,
            user=USER,
            password=PASSWORD,
            host=HOST,
            port=PORT,
            sslmode='disable',
            gssencmode='disable'""",
            min_size=4,
            max_size=10,
        )

        return pool



#ADD HERE -> WHAT WE ARE WAITING HERE
class PostgresDBTablesCreation():
    @staticmethod
    async def create(pool) -> None:

        logger.info('Creating the tables')

        async with pool.connection() as conn:
            async with conn.cursor() as cur:
                cur.begin()
                await conn.execute(text("""CREATE TABLE IF NOT EXISTS all_groups(
                    db_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    group_id INT NOT NULL,
                    group_name VARCHAR(10) NOT NULL,
                    faculty_id INT NOT NULL,
                    course INT NOT NULL
                )"""))

                await conn.execute(text("""CREATE TABLE IF NOT EXISTS groups_in_use(
                    db_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    group_id INT NOT NULL
                    group_name VARCHAR(10) NOT NULL,
                    faculty_id INT NOT NULL,
                    course INT NOT NULL
                )"""))
                
                conn.commit()

        logger.info('Tables created')


    @staticmethod
    async def fill_tables(pool, to_insert:list) -> None: #to_insert is list of dicts
        try:
            with pool.connection as conn:
                with conn.cursor as cur:
                    cur.executemany(text("INSERT INTO all_groups(group_id, group_name, faculty_id, course) VALUES (%s, %s, %s, %s)"), to_insert)
                    conn.commit()

        except Exception as e:
            logger.critical("Cant fill the tables", e=e)










    

    
