import sqlite3
import psycopg
import os
from dotenv import load_dotenv
from pathlib import Path


def migration():
    pass


CURRENT_FILE_PATH = Path(__file__).resolve()
SRC_DIR = next(p for p in CURRENT_FILE_PATH.parents if p.name == 'src')
DOTENV_PATH = SRC_DIR /'.env'

def main() -> None:
    try:
        print('trying load dot')
        load_dotenv(dotenv_path=DOTENV_PATH)
        print('dot laoded with:')

        print(os.getenv('DB_NAME'))
        print(os.getenv('DB_USER'))
        print(os.getenv('DB_PASSWORD'))
        print(os.getenv('DB_HOST'))
        print(os.getenv('DB_PORT'))

        print('try to connect')
        connection = psycopg.connect(

            dbname=os.getenv('DB_NAME'),
            user=os.getenv('DB_USER'),
            password=os.getenv('DB_PASSWORD'),
            host=os.getenv('DB_HOST'),
            port=os.getenv('DB_PORT'),
            sslmode='disable',
            gssencmode='disable'
        )
        print('connected')

        #pg_cur = connection.cursor()
        print('cur created')
          
        print('sqlite preparetion')
        conn = sqlite3.connect('temp_copy.db')
        lite_cur = conn.cursor()
        print('sqlite prepared!\n\n')


        with connection.cursor() as pg_cur:
            try:
                

                pg_cur.execute("""CREATE TABLE IF NOT EXISTS users(
                    db_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL UNIQUE,
                    course INT NOT NULL,
                    faculty VARCHAR(10) NOT NULL,
                    group_id INT NOT NULL,
                    last_time_active VARCHAR(20)
                )""")
                print('tables created')

                lite_cur.execute("SELECT user_id, course, faculty, group_id, last_time_active FROM users WHERE last_time_active IS NOT NULL") 
                data = lite_cur.fetchall()
                
                a = 0

                for i in data:
                    print(i)
                    if a == 6:
                        break

                    a = a + 1 

                pg_cur.executemany("INSERT INTO users (user_id, course, faculty, group_id, last_time_active) VALUES (%s, %s, %s, %s, %s)", data)
                print('insertion complete')

                connection.commit()

            except Exception as e:
                print(e)
            



        pg_cur.execute("SELECT version();")  
        print(pg_cur.fetchone())

    except Exception as e:
        print(f"{e}")

    #cur.execute()

main()
